version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: study_go_redis
    ports:
      - "6381:6379"
    volumes:
      - ./volumes/redis/d–∞ta:/root/redis
      - ./volumes/redis/local/redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '--port', '6381']
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # mysql
  mysql:
    image: mysql:8.0
    container_name: study_go_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
    ports:
      - '3308:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5