server:
  port: 6969
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
  
logger:
  log_level: debug
  file_log_name: "./storage/logs/dev.001.log"
  max_size:    500 
  max_backups: 3
  max_age:     28,  
  compress:   true